### ISSUE TITLE
Webpack compilation failed

### ISSUE THREAD

**Issue by nikolasp** [sanex3339/laravel-5-angular-2-example#3]
Just to test I've cloned this project, but this error when I run gulp is thrown.

`/home/vagrant/Code/laravel-5-angular-2-example/node_modules/laravel-elixir-webpack-ex/index.js:48
        (new Notification).error(e, 'Webpack Compilation Failed!');
         ^
TypeError: Notification is not a function
    at Stream.<anonymous> (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/laravel-elixir-webpack-ex/index.js:48:10)
    at emitOne (events.js:95:20)
    at Stream.emit (events.js:182:7)
    at /home/vagrant/Code/laravel-5-angular-2-example/node_modules/laravel-elixir-webpack-ex/node_modules/webpack-stream/index.js:112:14
    at Compiler.<anonymous> (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/webpack/lib/Compiler.js:187:11)
    at /home/vagrant/Code/laravel-5-angular-2-example/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.next (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/vagrant/Code/laravel-5-angular-2-example/node_modules/laravel-elixir-webpack-ex/node_modules/webpack-stream/index.js:153:7)`

**Comment by sanex3339** [comment]
This error caused by laravel-elixir-webpack-ex plugin, which incompatible with latest lavarel-elixir 6.0.0
I created issue https://github.com/farrrr/laravel-elixir-webpack-ex/issues/6 but not recieved a response, so, i think i downgrade laravel-elixir version to 5.*

**Comment by nikolasp** [comment]
Thanks

**Comment by sanex3339** [comment]
fixed in https://github.com/sanex3339/laravel-5-angular-2-example/commit/4455c170ce07ca4fe5e8ea389c1ea46f874faf9b
